version: "3.9"
services: 

  general-service:
    ports: 
      - "${EXTERNAL_PORT}:${PORT}"
    environment:
      PORT: "${PORT}"
      NODE_ENV: "${NODE_ENV}"
      NODEMAILER_SERVICE: "${NODEMAILER_SERVICE}"
      NODEMAILER_HOST: "${NODEMAILER_HOST}"
      NODEMAILER_PORT: "${NODEMAILER_PORT}"
      NODEMAILER_USER: "${NODEMAILER_USER}"
      NODEMAILER_PASS: "${NODEMAILER_PASS}"
      MONGO_DB_URI: "${MONGO_DB_URI}"
      MONGO_DB_NAME: "${MONGO_DB_NAME}"
      MONGO_DB_USER: "${MONGO_DB_USER}"
      MONGO_DB_PASS: "${MONGO_DB_PASS}"
      TEST_MONGO_DB_URL: "${TEST_MONGO_DB_URL}"
      TEST_MONGO_DB_NAME: "${TEST_MONGO_DB_NAME}"
      TEST_MONGO_DB_USER: "${TEST_MONGO_DB_USER}"
      TEST_MONGO_DB_PASS: "${TEST_MONGO_DB_PASS}"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_S3_BUCKET: "${AWS_S3_BUCKET}"
      AWS_ENDPOINT: "${AWS_ENDPOINT}"
      STRIPE_API_KEY: "${STRIPE_API_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"
      STRIPE_SESSION_CANCEL_URL: "${STRIPE_SESSION_CANCEL_URL}"
      STRIPE_SESSION_SUCCESS_URL: "${STRIPE_SESSION_SUCCESS_URL}"

  mongodb:
    ports:
      - "${MONGO_DB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  test-mongodb:
    ports:
      - "${TEST_MONGO_DB_PORT}:27017"
    environment:
      MONGO_INITDB_DATABASE: "${TEST_MONGO_INITDB_DATABASE}"
      MONGO_INITDB_ROOT_USERNAME: "${TEST_MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${TEST_MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DB_USER: "${TEST_MONGO_DB_USER}"
      MONGO_DB_PASS: "${TEST_MONGO_DB_PASS}"


